# ----------- CONFIGURABLE START -----------
title:            "Tonvchung"
description:      "侃侃理想、谈谈人生、敲敲代码。"
url:              https://tonvchung.github.io # 域名
signoff:          "tonvchung" # Your name
facebook_appid:   
google_analytics: 
share:            true 
# 分页
paginate: 15
paginate_path: "page=num"
gems: [jekyll-paginate]
links:
  # - name:         首页
  #   url:          /
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
